
[serve.static]
plugins = ["bun-plugin-tailwind", "./plugins/markdownAsText.ts"]
env = "BUN_PUBLIC_*"

# Preload runtime plugins so imports of .md resolve to strings in dev.
preload = ["./plugins/markdownAsText.ts"]
